In [1]:
import tensorflow as tf

### 创建张量

In [2]:
a = tf.constant([[1,2],[3,4]])

In [3]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

### 转换张量

In [4]:
b=tf.convert_to_tensor([1,2.])

In [5]:
b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

### 均匀分布

In [6]:
tf.random.uniform([2,2],0,1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.16045296, 0.24595141],
       [0.49065626, 0.55717766]], dtype=float32)>

### 正态分布

In [7]:
tf.random.normal([2,2],0,1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.65366614, -0.68616164],
       [-0.92417973,  0.10355356]], dtype=float32)>

### 索引

In [8]:
x = tf.random.normal([4,32,32,3],1,5)

In [10]:
x[0].shape

TensorShape([32, 32, 3])

In [11]:
x[0][1].shape

TensorShape([32, 3])

In [15]:
x[0][1][2].shape

TensorShape([3])

### 维度变换

In [21]:
e = tf.range(96)
e.shape

TensorShape([96])

In [20]:
x = tf.reshape(e,[2,-1,3])
x.shape

TensorShape([2, 16, 3])

In [30]:
X = tf.range(512)
X = tf.reshape(X,[16,32])
X.shape

TensorShape([16, 32])

In [37]:
W = tf.ones([32,8],dtype=tf.int32)
W.shape

TensorShape([32, 8])

In [38]:
b = tf.zeros([8],dtype=tf.int32)
b.shape

TensorShape([8])

In [44]:
Y = tf.add(tf.matmul(X,W),b)
Y

<tf.Tensor: shape=(16, 8), dtype=int32, numpy=
array([[  496,   496,   496,   496,   496,   496,   496,   496],
       [ 1520,  1520,  1520,  1520,  1520,  1520,  1520,  1520],
       [ 2544,  2544,  2544,  2544,  2544,  2544,  2544,  2544],
       [ 3568,  3568,  3568,  3568,  3568,  3568,  3568,  3568],
       [ 4592,  4592,  4592,  4592,  4592,  4592,  4592,  4592],
       [ 5616,  5616,  5616,  5616,  5616,  5616,  5616,  5616],
       [ 6640,  6640,  6640,  6640,  6640,  6640,  6640,  6640],
       [ 7664,  7664,  7664,  7664,  7664,  7664,  7664,  7664],
       [ 8688,  8688,  8688,  8688,  8688,  8688,  8688,  8688],
       [ 9712,  9712,  9712,  9712,  9712,  9712,  9712,  9712],
       [10736, 10736, 10736, 10736, 10736, 10736, 10736, 10736],
       [11760, 11760, 11760, 11760, 11760, 11760, 11760, 11760],
       [12784, 12784, 12784, 12784, 12784, 12784, 12784, 12784],
       [13808, 13808, 13808, 13808, 13808, 13808, 13808, 13808],
       [14832, 14832, 14832, 14832, 14832, 